<section>
    <h1>Contact</h1>
    <p>Pour toute questions, remarques, ... n'hésitez pas à me contacter à l'aide du formulaire.</p>
    <form>
        <div>
            <label for="lastname">Votre nom</label>
            <input type="text" id="lastname" name="lastname" required/>
        </div>
        <div>
            <label for="firstname">Votre prénom</label>
            <input type="text" id="firstname" name="firstname" required/>
        </div>
        <div>
            <label for="email">Votre email</label>
            <input type="email" id="email" name="email" required/>
        </div>
        <div>
            <label for="message">Votre message</label>
            <textarea id="message" name="message" rows="5" cols="33" required></textarea>
        </div>
        <div>
            <input type="submit" value="Envoyer"/>
        </div>
    </form>
</section>