<section class="contact">
    <form id="contact-form" class="form">
        <h1 class="form__title">CONTACT</h1>
        <p class="form__subtitle">Pour toute question, remarque, ... n'hésitez pas à me l'envoyer à l'aide de ce formulaire.</p>
        <div class="form__line">
            <input class="form__line__input" type="text" id="lastname" name="lastname" placeholder="Nom*" required>
        </div>
        <div class="form__line">
            <input class="form__line__input" type="text" id="firstname" name="firstname" placeholder="Prénom*" required>
        </div>
        <div class="form__line">
            <input class="form__line__input" type="email" id="email" name="email" placeholder="E-mail*" required>
        </div>
        <div class="form__line">
            <textarea class="form__line__input form__line__textarea" id="message" name="message" rows="10" placeholder="Message*" required></textarea>
        </div>
        <div class="form__line">
            <div class="form__line__checkbox">
                <input type="checkbox" id="send-copy" name="send-copy">
                <label for="send-copy">Envoyer une copie à mon adresse e-mail</label>
            </div>
        </div>
        <div class="form__buttons">
            <button class="button--mail" type="submit">ENVOYER</button>
        </div>
    </form>
</section>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.min.css" rel="stylesheet">
<script>
    var contactForm = $("#contact-form");
    contactForm.on("submit", function(e)
    {
    	e.preventDefault();

    	let url = new URL("/contact/send", window.location.origin);

    	$.post(url, contactForm.serialize(), function(data) 
    	{	
    		var result = JSON.parse(data);

      		if (result.success == true)
            {
                Swal.fire(
                {
                    icon: 'success',
                    title: 'Votre message a bien été envoyé.',
                })

                contactForm[0].reset();
            }
            else
            {
                Swal.fire(
                {
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Une erreur s\'est produite. Veuillez réessayer plus tard.'
                })
            }
    	});
    });    
</script>