<section>
    <h1>Parrainage</h1>
    <p>N'hésitez pas à me soutenir tout en faisant des économies grâce à ces différents liens de parrainage.</p>

    <section>
        <h2>Les banques</h2>
        <ol>
            <li>
                <img alt="Boursorama Banque">
                <p>Mon code parainage : ??? (Permet d'obtenir entre 80€ et 130€ de prime en fonction de la période)
                </br>
                <a href="https://www.boursorama-banque.com/">Site officiel</a></p>
                <p>Boursorama Banque est la banque en ligne la plus populaire -> TODO.</p>
            </li>
            <li>
                <img alt="Fortuneo Banque">
                <p> Mon code parainnage : ???
                </br>
                <a href="https://www.fortuneo.fr/">Site officiel</a></p>
                <p>Fortuneo Banque -> TODO.</p>
            </li>
        </ol>
    </section>
</section>