<?php
use \Framework\Tools\Helper\RoutesHelper;
?>

<section class="content l-content">
	<h1 class="h1">Calculette de l'impôt sur les primes d'intéressement et de participation</h1>
	<form class="form" id="calc-form">
		<div class="form-line">
			<label for="gross-amount" class="form-line-label">Montant brut de la prime en € : </label>
			<input type="text" id="gross-amount" name="gross-amount" class="form-line-input" required>
		</div>
		<div class="form-line">
			<label for="marginal-tax-bracket" class="form-line-label">Tranche marginal d'imposition : </label>
			<select name="marginal-tax-bracket" id="marginal-tax-bracket" class="form-line-input">
    			<option value="0">0%</option>
    			<option value="0.11" selected>11%</option>
    			<option value="0.30">30%</option>
    			<option value="0.45">45%</option>
			</select>
		</div>
		<div class="form-buttons">
			<input type="submit" value="Calculer" class="button--submit">
		</div>
	</form>

	<div id="result"></div>
</section>

<script>
let calcForm = $("#calc-form");
calcForm.on("submit", function(e)
{
	e.preventDefault();

	let url = new URL("/calculator/premium-tax/calc/json", window.location.origin);

	$.post(url, calcForm.serialize(), function(data) 
	{	
		var resultArea = $("#result");
		resultArea.addClass("result");

		var json = JSON.parse(data);

  		$("#result").html("<div class=\"result-content\"><div class=\"result-content-block\"><p>Pour une prime de " 
		+ json.grossAmount 
		+ "€ brut, vous toucherez réellement " + json.netAmount + "€.</p></div><div class=\"result-content-block\"><p>Avec une tranche marginale d'imposition à " 
		+ json.marginalTaxBracket * 100 
		+ "%, vous paierez " 
		+ json.incomeTax 
		+ "€ d'impôts sur le revenu en plus.</p></div></div>");
	});
});
</script>